
events {}

http {
    server {
        listen 80;

        server_name ~^(?<subdomain>.+)\.dev\.miapp\.com$;

        location / {
            proxy_pass http://odoo_instance_DEVELOPMENT_${subdomain}:8069;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }

    server {
        listen 80;

        server_name ~^(?<subdomain>.+)\.stg\.miapp\.com$;

        location / {
            proxy_pass http://odoo_instance_STAGING_${subdomain}:8069;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }

    server {
        listen 80;

        server_name ~^(?<subdomain>.+)\.miapp\.com$;

        location / {
            proxy_pass http://odoo_instance_PRODUCTION_${subdomain}:8069;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
