events {}

http {
    server {
        listen 80;

        # DEVELOPMENT: ejemplo pruebafinal-staging02.dev.miapp.com
        server_name ~^(?<instance>.+?)\.dev\.miapp\.com$;

        location / {
            set $container_name odoo_instance_DEVELOPMENT_${instance};
            proxy_pass http://$container_name:8069;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }

    server {
        listen 80;

        # STAGING: ejemplo pruebafinal-staging02.staging.miapp.com
        server_name ~^(?<instance>.+?)\.staging\.miapp\.com$;

        location / {
            set $container_name odoo_instance_STAGING_${instance};
            proxy_pass http://$container_name:8069;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }

    server {
        listen 80;

        # PRODUCTION: ejemplo pruebafinal-staging02.miapp.com
        server_name ~^(?<instance>.+?)\.miapp\.com$;

        location / {
            set $container_name odoo_instance_PRODUCTION_${instance};
            proxy_pass http://$container_name:8069;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}
