# Configuraci?n de PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/TesisOdoo
spring.datasource.username=userTesis
spring.datasource.password=123456789
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Configuraci?n de GitHub
github.local.repo.path=C:\\Users\\paul-\\2025\\Maestria\\Tesis\\Github\\TesisMaestria
github.username=Paulguzhnay
github.token=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

# Configuraci?n para Docker
docker.host=npipe:////./pipe/docker_engine
docker.network=odoo_network
docker.image=odoo:17
docker.postgres.image=postgres:15
docker.postgres.user=odoo
docker.postgres.password=odoo
docker.postgres.db=postgres
docker.container.prefix=odoo_instance_

# Instancias Odoo
docker.image.development=odoo:17
docker.image.staging=odoo:17
docker.image.production=odoo:17
docker.postgres.shared.container=odoo_shared_db
docker.postgres.shared.dbname=TesisOdoo

backup.directory=${user.home}/odoo-backups

#JWT
jwt.secret=odoo_clave_cuenca_ciudad_2025202520205

# Límite de subida de archivos (hasta 100 MB por archivo y petición)
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

spring.security.oauth2.client.registration.github.client-id=Ov23li4hBkj65uMbYvc6
spring.security.oauth2.client.registration.github.client-secret=f392bcbcf77f0507955f489f20fa86125fcd01a2
spring.security.oauth2.client.registration.github.redirect-uri=http://localhost:4200/github-callback
spring.security.oauth2.client.registration.github.scope=read:user,repo