spring.datasource.url=jdbc:postgresql://localhost:5432/TesisOdoo
spring.datasource.username=userTesis
spring.datasource.password=123456789
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
github.local.repo.path=C:\\Users\\paul-\\2025\\Maestria\\Tesis\\Github\\TesisMaestria
github.username=Paulguzhnay
github.token=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
